name: cherrypic
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8 # iOS 스타일 아이콘
    sign_in_with_apple: ^7.0.1 # Apple 로그인
    flutter_web_auth_2: ^4.1.0
    # Architecture
    provider: ^6.1.1 # 상태 관리 (MVVM ViewModel 연동)
    # Networking
    dio: ^5.4.1 # API 통신 및 멀티파트 이미지 업로드
    # Routing
    go_router: ^14.0.1 # 화면 라우팅 및 딥링크 지원
    # 이미지 처리
    photo_manager: ^3.0.0 # 갤러리 접근 및 다중 이미지 선택
    flutter_image_compress: ^2.1.0 # 이미지 압축 처리
    cached_network_image: ^3.3.1 # 네트워크 이미지 캐싱 및 최적화
    percent_indicator: ^4.2.2 #게이지 바

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/

    fonts:
        - family: Koulen
          fonts:
              - asset: assets/fonts/Koulen-Regular.ttf
